{
 "title": "server",
 "description": "Monitor Linux host (VM, Server, OS), your personal machines with preconfigured beautiful dashboard.",
 "tags": [
  "linux",
  "node_exporter"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
   },
   {
    "name": "network_interface",
    "label": "Network:",
    "query": "label_values(node_network_info{operstate=\"up\"}, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_speed_bytes{device=\"$network_interface\", instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "Hardware temperature",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    }
   ]
  },
  {
   "title": "Network Traffic In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"$network_interface\",instance=~'$node'}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "bargauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Network Traffic Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"$network_interface\",instance=~'$node'}"
    }
   ]
  },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 } },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    }
   ]
  },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 } },
  {
   "title": "Space available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs',mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "UDP Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_sockstat_UDP_inuse{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    }
   ]
  },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 15, "y": 13 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 18, "y": 13 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 } },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 } },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 16 } }
 ]
}